# -*- coding: utf-8 -*-
"""Sales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LcdirqNWeI7jo5VWMjnAEHoOUC4kB17D
"""

import pandas as pd


data = {
    "price": [10, 20, 15, 30, None, -5],
    "quantity": [1, 2, 3, 1, 2, 5]
}

pd.DataFrame(data).to_csv("sales.csv", index=False)


class SalesDS:

    def __init__(self, filepath):
        self.df = pd.read_csv(filepath)

    def clean(self):
        self.df = self.df.dropna()
        self.df = self.df[self.df["price"] > 0]
        self.df = self.df[self.df["quantity"] > 0]

    def add_total_column(self):
        self.df["Total"] = self.df["price"] * self.df["quantity"]

    def total_revenue(self):
        return self.df["Total"].sum()

    def show(self):
        print(self.df)



ds = SalesDS("sales.csv")

ds.clean()
ds.add_total_column()
ds.show()

print("Total revenue: $", ds.total_revenue())































